# # This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# # Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# # See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   node: circleci/node@4.7

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#     # Inside the workflow, you define the jobs you want to run.
#     jobs:
#       - node/test:
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
#           version: '16.10'
#           # If you are using yarn, change the line below from "npm" to "yarn"
#           pkg-manager: npm


version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: sudo apt-get install rsync && rsync --version
            - run: rsync -a -e "ssh -o StrictHostKeyChecking=no" dist/ centos@X.XX.XXX.XXX:~/reactfrontend/
            - run:
                name: Deploy Final
                command: |
                  ssh centos@X.XX.XXX.XXX "sudo rsync -a /home/centos/reactfrontend/ /usr/share/nginx/html/"
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy:
            filters:
              branches:
                only: circleci-project-setup # only deploy on the master branch琀