version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy:
            filters:
              branches:
                only: main
