version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: sudo apt-get install rsync && rsync --version
            - run: rsync -a -e "ssh -o StrictHostKeyChecking=no" dist/ centos@X.XX.XXX.XXX:~/reactfrontend/
            - run:
                name: Deploy Final
                command: |
                  ssh centos@X.XX.XXX.XXX "sudo rsync -a /home/centos/reactfrontend/ /usr/share/nginx/html/"
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy:
            filters:
              branches:
                only: main
